### ISSUE TITLE
Test fails on rakudist

### ISSUE THREAD

**Issue by melezhik** [titsuki/raku-Algorithm-ZhangShasha#1]
http://repo.westus.cloudapp.azure.com/sparky/report/debian/269

21:46:40 05/04/2020 [bash: zef install Algorithm::ZhangShasha] [Algorithm::ZhangShasha] Could not find DOM::Tiny in:
21:46:40 05/04/2020 [bash: zef install Algorithm::ZhangShasha] [Algorithm::ZhangShasha]     file#/home/ovjjkrorkb/.zef/store/Algorithm-ZhangShasha-0.0.2.tar.gz/Algorithm-ZhangShasha-0.0.2
21:46:40 05/04/2020 [bash: zef install Algorithm::ZhangShasha] [Algorithm::ZhangShasha]     inst#/home/ovjjkrorkb/.raku
21:46:40 05/04/2020 [bash: zef install Algorithm::ZhangShasha] [Algorithm::ZhangShasha]     inst#/opt/rakudo-pkg/share/perl6/site
21:46:40 05/04/2020 [bash: zef install Algorithm::ZhangShasha] [Algorithm::ZhangShasha]     inst#/opt/rakudo-pkg/share/perl6/vendor
21:46:40 05/04/2020 [bash: zef install Algorithm::ZhangShasha] [Algorithm::ZhangShasha]     inst#/opt/rakudo-pkg/share/perl6/core
21:46:40 05/04/2020 [bash: zef install Algorithm::ZhangShasha] [Algorithm::ZhangShasha]     ap#
21:46:40 05/04/2020 [bash: zef install Algorithm::ZhangShasha] [Algorithm::ZhangShasha]     nqp#
21:46:40 05/04/2020 [bash: zef install Algorithm::ZhangShasha] [Algorithm::ZhangShasha]     perl5#
21:46:40 05/04/2020 [bash: zef install Algorithm::ZhangShasha] [Algorithm::ZhangShasha] at /home/ovjjkrorkb/.zef/store/Algorithm-ZhangShasha-0.0.2.tar.gz/Algorithm-ZhangShasha-0.0.2/t/01-basic.t:4
21:46:40 05/04/2020 [bash: zef install Algorithm::ZhangShasha] ===> Testing [FAIL]: Algorithm::ZhangShasha:ver<0.0.2>:auth<cpan:TITSUKI>
21:46:40 05/04/2020 [bash: zef install Algorithm::ZhangShasha] task exit status: 1

**Comment by titsuki** [comment]
@melezhik Thanks for your report. I added missing `DOM::Tiny` since version `0.0.3`.

**Comment by melezhik** [comment]
@titsuki you are welcome. you can always test distributions using rakudist - http://repo.westus.cloudapp.azure.com/rakudist

**Comment by titsuki** [comment]
@melezhik current 0.0.3 builds fine. So I'll close this issue: http://repo.westus.cloudapp.azure.com/sparky/report/debian/275
